### PR TITLE
Fixed bug for matching vg names.

### PR DESCRIPTION
**Pull request by billcarlson**
If have vgs named 'system' and 'system_data', checking size specifically for 'system' will incorrectly calculate size information as check ends up matching both vgs.

### CODE REVIEW

**Comment by veverjak** [comment]
@billcarlson there seems to be some conflicts, could you resolve it? 

Also I can't test this any more, would you be interested in managing this repo?

**Comment by billcarlson** [comment]
I'm working on resolution.

Curious, have you noted a platform that allows spaces or other 
characters in volume group names that require quotes? Not clear why 
quotes were added to variables with volume group names.

Linux specifically limits to [a-zA-Z0-9.-_+].

I'm willing to manage repo as well.

Thanks,

-- 

Bill Carlson

Anything is possible, given Time and Money.

**Comment by veverjak** [comment]
@billcarlson could you delete your fork for a while, I can't transfer it on you because you already have a fork. 

vgsize

**Comment by billcarlson** [comment]
Fork deleted.

-- 

Bill Carlson

Anything is possible, given Time and Money.

**Pull request closed without merging**
